name: Deploy
concurrency:
  group: ${{ github.workflow }}

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          #Java 8 + Remove old build
          - os: ubuntu-latest
            java: 8
            profile: jpackager-java8
            name: Java 8 
            distribution: 'temurin'
          #Linux
          - os: ubuntu-latest
            java: 17
            profile: jpackager-deploy
            name: Linux
            distribution: 'oracle'
          #Windows
          - os: windows-latest
            java: 17
            profile: jpackager-deploy
            name: Windows
            distribution: 'oracle'
          #MacOS
          - os: macos-latest
            java: 17
            profile: jpackager-deploy
            name: MacOS
            distribution: 'oracle'
    name: ${{ matrix.name }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Cache
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ matrix.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ matrix.os }}-maven-
    - name: JDK
      uses: actions/setup-java@v2
      with:
        distribution: ${{ matrix.distribution }}
        java-version: ${{ matrix.java }}
    - name: Build with Maven
      run: mvn -s settings.xml clean deploy -DskipTests -P ${{ matrix.profile }} "-Dftp.user=${{secrets.ftpuser}}" "-Dftp.pass=${{secrets.ftppass}}" "-Dftp.host=${{secrets.ftphost}}" "-Dftp.file=${{secrets.ftpfile}}"  "-Dftp.delete=${{secrets.ftpdelete}}"
    - name: Release
      uses: ncipollo/release-action@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        allowUpdates: true
        replacesArtifacts: true
        artifacts: "target/installer/*.*"
        token: ${{ secrets.GITHUB_TOKEN }}
