name: Test macOS

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [ 8, 11, 13 ]
    name: macOS (Java ${{ matrix.java }})
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml